### ISSUE TITLE
One or more blueprints has an unresolved compiler error...

### ISSUE THREAD

**Issue by alajom** [ser432poly/Group2#9]
Unable to play tutorial level to test HUD. 

It doesn't like the Room_BP Blueprint. I keep getting a message:
"Blueprint could not be loaded because it derives from an invalid class.  Check to make sure the parent class for this blueprint hasn't been removed!"

**Comment by EdwinAvalos7** [comment]
Compile the code and make sure you can see the room cpp file

**Comment by alajom** [comment]
The compile button isn't showing up in Unreal?!
